import type {Metadata} from "next";
import SideBar from "./components/sidebar/Sidebar";
import "./globals.css";
import {Bebas_Neue, Oswald} from "next/font/google";

// Importando as fontes
const titulo = Bebas_Neue({weight: "400", subsets: ["latin"], variable: "--font-titulo"});
const subttitulo = Oswald({weight: ["200", "400", "700"], subsets: ["latin"], variable: "--font-subtitulo"});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const imageUrl = "/image/Gemini_Generated_Image_3aq5973aq5973aq5.png";

    return (
        <html lang="pt-br">
            <body className={`${titulo.variable} ${subttitulo.variable} antialiased`}>
                <div className="flex flex-col">
                    <SideBar />
                    <main
                        className="ml-72 min-h-screen bg-no-repeat bg-cover bg-center "
                        style={{backgroundImage: `url('${imageUrl}')`}}
                    >
                        {children}
                    </main>
                </div>
            </body>
        </html>
    );
}
